/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
// This code is auto-generated by Plasmic; please do not edit!
// Plasmic Project: xht6ggYXPaEbYDhYJJ7oxU
import { createUseStyleTokens } from "@plasmicapp/react-web";
import { _useGlobalVariants } from "./plasmic"; // plasmic-import: xht6ggYXPaEbYDhYJJ7oxU/projectModule
import "./plasmic.css"; // plasmic-import: xht6ggYXPaEbYDhYJJ7oxU/projectcss

const data = {
  base: `${"plasmic_tokens_xht6ggYXPaEbYDhYJJ7oxU"}`,
  varianted: []
};

export const _useStyleTokens = createUseStyleTokens(data, _useGlobalVariants);
