/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
// This code is auto-generated by Plasmic; please do not edit!
// Plasmic Project: cVYcH3SGzTaSfRP6RWBBuV
import { createUseStyleTokens } from "@plasmicapp/react-web";
import { _useGlobalVariants } from "./plasmic"; // plasmic-import: cVYcH3SGzTaSfRP6RWBBuV/projectModule
import "./plasmic.css"; // plasmic-import: cVYcH3SGzTaSfRP6RWBBuV/projectcss
import "../antd_5_hostless/plasmic.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss

const data = {
  base: `${"plasmic_tokens_cVYcH3SGzTaSfRP6RWBBuV"} ${"plasmic_tokens_ohDidvG9XsCeFumugENU3J"}`,
  varianted: []
};

export const _useStyleTokens = createUseStyleTokens(data, _useGlobalVariants);
