/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: cVYcH3SGzTaSfRP6RWBBuV
// Component: 989bfyKEPENd
import * as React from "react";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  generateOnMutateForSpec,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  initializeCodeComponentStates,
  renderPlasmicSlot,
  useDollarState
} from "@plasmicapp/react-web";
import { useDataEnv } from "@plasmicapp/react-web/lib/host";
import { BasePopover } from "@plasmicpkgs/react-aria/skinny/registerPopover";
import { BaseListBox } from "@plasmicpkgs/react-aria/skinny/registerListBox";
import { listboxHelpers as BaseListBox_Helpers } from "@plasmicpkgs/react-aria/skinny/registerListBox";
import MenuItem from "../../MenuItem"; // plasmic-import: Ht2V-dblfiHr/component
import MenuSection from "../../MenuSection"; // plasmic-import: k5pQxmQZhsbJ/component
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: cVYcH3SGzTaSfRP6RWBBuV/styleTokensProvider
import "@plasmicapp/react-web/lib/plasmic.css";
import "./plasmic.css"; // plasmic-import: cVYcH3SGzTaSfRP6RWBBuV/projectcss
import sty from "./PlasmicMenuPopover.module.css"; // plasmic-import: 989bfyKEPENd/css

createPlasmicElementProxy;

export const PlasmicMenuPopover__VariantProps = new Array();

export const PlasmicMenuPopover__ArgProps = new Array(
  "offset",
  "menuItems",
  "initialSelectedKey"
);

const $$ = {};

function PlasmicMenuPopover__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const args = React.useMemo(
    () =>
      Object.assign(
        {
          offset: 2
        },
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );
  const $props = {
    ...args,
    ...variants
  };
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  const stateSpecs = React.useMemo(
    () => [
      {
        path: "ariaListBox.selectedValue",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) =>
          $props["initialSelectedKey"],
        onMutate: generateOnMutateForSpec("selectedValue", BaseListBox_Helpers)
      }
    ],

    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $q: {},
    $refs
  });
  const styleTokensClassNames = _useStyleTokens();
  return (
    <BasePopover
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        "__wab_instance",
        "root_reset_cVYcH3SGzTaSfRP6RWBBuV",
        "plasmic_default_styles",
        "plasmic_mixins",
        styleTokensClassNames,
        sty.root
      )}
      matchTriggerWidth={true}
      offset={args.offset}
      placement={"bottom"}
      resetClassName={classNames(
        "root_reset_cVYcH3SGzTaSfRP6RWBBuV",
        "plasmic_default_styles",
        "plasmic_mixins",
        styleTokensClassNames
      )}
      shouldFlip={true}
    >
      {(() => {
        const child$Props = {
          className: classNames("__wab_instance", sty.ariaListBox),
          defaultSelectedKeys: args.initialSelectedKey,
          onSelectionChange: async (...eventArgs) => {
            generateStateOnChangePropForCodeComponents(
              $state,
              "selectedValue",
              ["ariaListBox", "selectedValue"],
              BaseListBox_Helpers
            ).apply(null, eventArgs);
          },
          selectedKeys: generateStateValueProp($state, [
            "ariaListBox",
            "selectedValue"
          ]),
          selectionMode: "single"
        };
        initializeCodeComponentStates(
          $state,
          [
            {
              name: "selectedValue",
              plasmicStateName: "ariaListBox.selectedValue"
            }
          ],

          [],
          BaseListBox_Helpers ?? {},
          child$Props
        );
        return (
          <BaseListBox
            data-plasmic-name={"ariaListBox"}
            data-plasmic-override={overrides.ariaListBox}
            {...child$Props}
          >
            {renderPlasmicSlot({
              defaultContents: (
                <React.Fragment>
                  <MenuItem
                    className={classNames(
                      "__wab_instance",
                      sty.menuItem__jv0P4
                    )}
                    value={"item1"}
                  />

                  <MenuItem
                    className={classNames(
                      "__wab_instance",
                      sty.menuItem__otayv
                    )}
                    label={"Item 2"}
                    value={"item2"}
                  />

                  <MenuItem
                    className={classNames(
                      "__wab_instance",
                      sty.menuItem__fDGz6
                    )}
                    label={"Item 3"}
                    value={"item3"}
                  />

                  <MenuSection
                    className={classNames(
                      "__wab_instance",
                      sty.menuSection___4Oaks
                    )}
                    items={
                      <React.Fragment>
                        <MenuItem
                          label={"Section Item 1"}
                          value={"section-item-1"}
                        />

                        <MenuItem
                          label={"Section Item 2"}
                          value={"section-item-2"}
                        />

                        <MenuItem
                          label={"Section Item 3"}
                          value={"section-item-3"}
                        />
                      </React.Fragment>
                    }
                  />
                </React.Fragment>
              ),

              value: args.menuItems
            })}
          </BaseListBox>
        );
      })()}
    </BasePopover>
  );
}

const PlasmicDescendants = {
  root: ["root", "ariaListBox"],
  ariaListBox: ["ariaListBox"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicMenuPopover__ArgProps,
          internalVariantPropNames: PlasmicMenuPopover__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicMenuPopover__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicMenuPopover";
  } else {
    func.displayName = `PlasmicMenuPopover.${nodeName}`;
  }
  return func;
}

export const PlasmicMenuPopover = Object.assign(
  // Top-level PlasmicMenuPopover renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    ariaListBox: makeNodeComponent("ariaListBox"),
    // Metadata about props expected for PlasmicMenuPopover
    internalVariantProps: PlasmicMenuPopover__VariantProps,
    internalArgProps: PlasmicMenuPopover__ArgProps
  }
);

export default PlasmicMenuPopover;
/* prettier-ignore-end */
