/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
// This code is auto-generated by Plasmic; please do not edit!
// Plasmic Project: cVYcH3SGzTaSfRP6RWBBuV
import * as React from "react";
import { AntdConfigProvider } from "@plasmicpkgs/antd5/skinny/registerConfigProvider";
import { EmbedCss } from "@plasmicpkgs/plasmic-embed-css";

export default function GlobalContextsProvider(props) {
  const { children, antdConfigProviderProps, embedCssProps } = props;
  return (
    <AntdConfigProvider
      {...antdConfigProviderProps}
      borderRadius={
        antdConfigProviderProps && "borderRadius" in antdConfigProviderProps
          ? antdConfigProviderProps.borderRadius
          : 6
      }
      colorBgBase={
        antdConfigProviderProps && "colorBgBase" in antdConfigProviderProps
          ? antdConfigProviderProps.colorBgBase
          : "#ffffff"
      }
      colorError={
        antdConfigProviderProps && "colorError" in antdConfigProviderProps
          ? antdConfigProviderProps.colorError
          : "#ff4d4f"
      }
      colorInfo={
        antdConfigProviderProps && "colorInfo" in antdConfigProviderProps
          ? antdConfigProviderProps.colorInfo
          : "#1677ff"
      }
      colorPrimary={
        antdConfigProviderProps && "colorPrimary" in antdConfigProviderProps
          ? antdConfigProviderProps.colorPrimary
          : "#1677ff"
      }
      colorSuccess={
        antdConfigProviderProps && "colorSuccess" in antdConfigProviderProps
          ? antdConfigProviderProps.colorSuccess
          : "#52c41a"
      }
      colorWarning={
        antdConfigProviderProps && "colorWarning" in antdConfigProviderProps
          ? antdConfigProviderProps.colorWarning
          : "#faad14"
      }
      controlHeight={
        antdConfigProviderProps && "controlHeight" in antdConfigProviderProps
          ? antdConfigProviderProps.controlHeight
          : 32
      }
      defaultDark={
        antdConfigProviderProps && "defaultDark" in antdConfigProviderProps
          ? antdConfigProviderProps.defaultDark
          : false
      }
      lineWidth={
        antdConfigProviderProps && "lineWidth" in antdConfigProviderProps
          ? antdConfigProviderProps.lineWidth
          : 1
      }
      loadingText={
        antdConfigProviderProps && "loadingText" in antdConfigProviderProps
          ? antdConfigProviderProps.loadingText
          : undefined
      }
      removeLoading={
        antdConfigProviderProps && "removeLoading" in antdConfigProviderProps
          ? antdConfigProviderProps.removeLoading
          : undefined
      }
      sizeStep={
        antdConfigProviderProps && "sizeStep" in antdConfigProviderProps
          ? antdConfigProviderProps.sizeStep
          : 4
      }
      sizeUnit={
        antdConfigProviderProps && "sizeUnit" in antdConfigProviderProps
          ? antdConfigProviderProps.sizeUnit
          : 4
      }
      themeStyles={
        antdConfigProviderProps && "themeStyles" in antdConfigProviderProps
          ? antdConfigProviderProps.themeStyles
          : true
            ? {
                fontFamily: "Inter",
                fontSize: "16px",
                fontWeight: "400",
                lineHeight: "1.5",
                color: "#000000",
                letterSpacing: "normal"
              }
            : undefined
      }
      wireframe={
        antdConfigProviderProps && "wireframe" in antdConfigProviderProps
          ? antdConfigProviderProps.wireframe
          : false
      }
    >
      <EmbedCss
        {...embedCssProps}
        css={
          embedCssProps && "css" in embedCssProps
            ? embedCssProps.css
            : '.acryllic{\r\nbackground: rgba(255, 255, 255, 0.15);\r\nbackdrop-filter: blur(25px) saturate(200%);\r\n-webkit-backdrop-filter: blur(25px) saturate(200%);\r\nborder: 1px solid rgba(255, 255, 255, 0.25);\r\nbox-shadow: 0 8px 32px rgba(0, 0, 0, 0.2);\r\n}\r\n\r\n.acryllic-dark {\r\n  position: relative;\r\n  background: rgba(255, 255, 255, 0.15);\r\n  backdrop-filter: blur(25px) saturate(200%);\r\n  -webkit-backdrop-filter: blur(25px) saturate(200%);\r\n  border: 1px solid rgba(255, 255, 255, 0.25);\r\n  box-shadow: 0 8px 32px rgba(0, 0, 0, 0.2);\r\n  border-bottom-left-radius: 20px;\r\n  border-bottom-right-radius: 20px;\r\n  border-top: 0;\r\n  }\r\n\r\n.acryllic-dark::before {\r\n  content: "";\r\n  position: absolute;\r\n  inset: 0;\r\n  background: rgba(0, 0, 0, 0.6);\r\n  pointer-events: none;\r\n  border-bottom-left-radius: 20px;\r\n  border-bottom-right-radius: 20px;\r\n}\r\n\r\n.textbox{\r\nbackground: rgba(255, 255, 255, 0.12);\r\nbackdrop-filter: blur(15px) saturate(200%);\r\n-webkit-backdrop-filter: blur(15px) saturate(200%);\r\nborder: 1px solid rgba(255, 255, 255, 0.3);\r\nborder-radius: 10px;\r\ncolor: #ffffff;\r\npadding: 14px 18px;\r\nfont-size: 18px;\r\noutline: none;\r\n}\r\n\r\n.correct-box{\r\nbackground: rgba(40, 200, 100, 0.30);\r\nbackdrop-filter: blur(15px) saturate(200%);\r\n-webkit-backdrop-filter: blur(15px) saturate(200%);\r\nborder: 1px solid rgba(100, 255, 150, 0.3);\r\nborder-radius: 10px;\r\ncolor: #ffffff;\r\n}\r\n\r\n.wrong-box{\r\n  background: rgba(200, 40, 40, 0.30);\r\nbackdrop-filter: blur(15px) saturate(200%);\r\n-webkit-backdrop-filter: blur(15px) saturate(200%);\r\nborder: 1px solid rgba(255, 100, 100, 0.3);\r\nborder-radius: 10px;\r\ncolor: #ffffff;\r\n}'
        }
      >
        {children}
      </EmbedCss>
    </AntdConfigProvider>
  );
}
